title: Gregory Gandy
logo: "/images/round_profile.png?raw=true"
description: >
  About
  <br><br>
  Data Analyst Skills
  * Excel
  * SQL
  * Power BI
  <br><br>
  <a href="https://www.linkedin.com/in/greg-gandy">View LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-R95KVXFX4M
